### PR TITLE
Fix bundling

### PR DESCRIPTION
**Pull request by dippi**
Bundling with a transpiler was failing (probably some bug in System Builder esm compiler).
If you need more details to replicate the issue, I'll be glad to help.

### CODE REVIEW

**Comment by dippi** [comment]
Ps: I replaced the chain of `.replace` with a `JSON.stringify`..it sould do.

**Comment by guybedford** [comment]
Thanks I've manually pushed a new release with the reversion.

**Comment by dippi** [comment]
Nice, thanks for the responsiveness!

But I'd like to know, why did you keep that odd chain of `.replace` instead of `JSON.stringify`?
And finally, when loaded in the browser, isn't it simpler to just define `instantiate` and return the plain source? (As it was in the first commits)

**Comment by guybedford** [comment]
Sure, great point I've pushed out a version with just JSON.stringify. The reason we use translate is because that is a single approach that works both in the browser and for builds (most importantly).

**Pull request closed without merging**
